concrete_setup_environment() {
    local tap_functions="/share/doc/slurm/tap_functions"

    if [ ! -f "${tap_functions}" ]; then
        echo "ERROR: TAP functions not found: ${tap_functions}"
        return 1
    fi

    . "${tap_functions}"

    mkdir -p "${HOME}/.tap"
}

concrete_prepare_apptainer() {
    export APPTAINER_CACHEDIR=${APPTAINER_CACHEDIR:-/work/projects/aci/cic/apps/flexserv}
    mkdir -p "$APPTAINER_CACHEDIR"

    module load tacc-apptainer
    module unload xalt
}

concrete_setup_cert_tls() {
    local certfile

    # CERTFILE generated by TAP
    certfile="$(cat "${HOME}/.tap/.${SLURM_JOB_ID}")"
    if [ ! -f "${certfile}" ]; then
        echo "TACC: ERROR - could not find TLS cert for secure session"
        return 1
    fi

    if [ "$ENABLE_HTTPS" -ne 0 ]; then
        export TLS_CERT="${certfile}"
        export TLS_KEY="${FLEXSERV_KEYFILE:-${certfile}}"
    fi
}

concrete_setup_random_token() {
    # Random token generated by TAP
    export RAND_TOKEN="$(tap_get_token)"
    if [ -z "${RAND_TOKEN}" ]; then
        echo "TACC: ERROR - could not generate token for app session"
        return 1
    fi
}

concrete_setup_login_port() {
    # This is the remote port users will hit (on login nodes)
    export LOGIN_PORT="$(tap_get_port)"
}

concrete_setup_reverse_tunnels() {
    local i

    # Create a reverse tunnel on each login node (login1..4)
    for i in 1 2 3 4; do
        ssh -o StrictHostKeyChecking=no \
            -o ConnectTimeout=3 \
            -o ExitOnForwardFailure=yes \
            -q -f -g -N \
            -R "${LOGIN_PORT}:${NODE_HOSTNAME_PREFIX}:${LOCAL_PORT}" \
            "login${i}" || true
    done
}

concrete_cleanup_site_resources() {
    if [ -n "${LOGIN_PORT:-}" ]; then
        tap_release_port "${LOGIN_PORT}" || true
    fi
}
